## PROCESSAMENTO DOS DADOS
Este notebook visa ler os dados de bares e restaurantes, extrair suas coordenadas geográficas usando a API da ```geocode.maps.co``` e formar um novo conjunto de dados apenas com as informações necessárias.

### 1- Leitura e Filtragem inicial
Aqui usamos a biblioteca pandas para ler o arquivo ```bares.csv``` e filtrar algumas colunas que não vamos precisar, além de mostrar quais os tipos de descrição de logradouro, pois é necessário convertê-los para o nome completo na hora da query.

In [3]:
import pandas as pd
from pathlib import Path

In [2]:
ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
RAW_DIR = ROOT / "data" / "raw"
PRC_DIR = ROOT / "data" / "processed"

In [3]:
bar_table = pd.read_csv(f"{RAW_DIR}/bares.csv")
colunas_rem = ["CNAE_PRINCIPAL", "DESCRICAO_CNAE_PRINCIPAL"]
bar_table = bar_table.drop(columns=colunas_rem)
bar_table.head(5)

,_id,DESC_LOGRADOURO,NOME_LOGRADOURO,NUMERO_IMOVEL,COMPLEMENTO,NOME_BAIRRO,NOME,NOME_FANTASIA
0,12,AVE,PORTUGAL,4316,NaN,JARDIM ATLANTICO,BAR E CAFE DONATELO LTDA,NaN
1,32,RUA,VINTE E OITO DE SETEMBRO,606,NaN,ESPLANADA,PALLATE COMERCIO DE PRODUTOS ALIMENTICIOS LTDA,PALLATE
2,40,AVE,EDGAR DA MATA MACHADO,390,A,DOM CABRAL,FABIO KALKS KOSCKY,BAR DO FABIO
3,58,AVE,DOS BANDEIRANTES,1839,NaN,CRUZEIRO,NECTAR DA SERRA LTDA,NECTAR DA SERRA
4,60,RUA,DO OURO,1428,NaN,SERRA,MERCEARIA DA SERRA LTDA,BAR E MERCEARIA DA SERRA

In [4]:
# Análise de descrição de logradouros
bar_table[["_id", "DESC_LOGRADOURO"]].groupby("DESC_LOGRADOURO").count()

                   _id
DESC_LOGRADOURO
ALA                 32
AVE               4604
BEC                114
EST                 25
PCA                190
ROD                171
RUA              15709
TRV                 10
VDP                  1
VIA                  3

In [5]:
null_report = (bar_table.isna().mean().mul(100).round(2).sort_values(ascending=False).reset_index())
null_report.columns = ["column", "null_percent"]
null_report[null_report["null_percent"] > 0].head(20)

          column  null_percent
0    COMPLEMENTO         52.98
1  NOME_FANTASIA         45.29

### 2- Extração das Coordenadas
A extração das coordenadas a partir dos endereços é feita pela API da ```geocode.maps.co```. É necessário ter uma conta e ajustar os valores dentro das células de acordo com a sua conta.
No entanto, não recomendo rodar o script se ```cords.json``` já existir em ```data/processed```, pois leva horas para extrair cada coordenada geográfica de todos os endereços.

In [12]:
import time
import json
import os
import requests as req

In [7]:
CORDS_DIR = f"{PRC_DIR}/cords.json"
FDATA_DIR = f"{PRC_DIR}/fulldata.json"

# Parâmetros - Altere os valores aqui
api_key = ""                # Coloque a sua API key aqui
sleep_time = 0.25           # Tempo entre uma request e outra, varia de acordo com a licença
CONSULTAS = len(bar_table)  # len(bar_table) para tudo

In [ ]:
url = "https://geocode.maps.co/search"
cols = ["DESC_LOGRADOURO", "NOME_LOGRADOURO", "NUMERO_IMOVEL"]

# Dicionários que serão escritos nos json mais tarde
if os.path.exists(CORDS_DIR):
    try:
        with open(CORDS_DIR, "r", encoding="utf-8") as f:
            cords_data = json.load(f)
    except Exception as e:
        print("Unable to load previous data:", e)
        cords_data = {}

else:
    cords_data = {}

# Mantém contagem de sucessos e falhas nas consultas
successes = 0
fails = 0

# Consultas
for i in range(CONSULTAS):
    # Caso o endereço já tenha sido processado
    if str(i) in cords_data:
        continue

    bar = bar_table.iloc[i]
    bar_name = bar["NOME"]
    bar_fantasia = bar["NOME_FANTASIA"]
    bar_fantasia = str(bar_fantasia) if pd.notna(bar_fantasia) else ""

    desc, logr, numi = [bar[cols[j]] for j in range(len(cols))]

    # Conversão do nome inteiro do tipo de logradouro
    match desc:
        case "AVE":
            desc = "AVENIDA"
        case "ALA":
            desc = "ALAMEDA"
        case "BEC":
            desc = "BECO"
        case "EST":
            desc = "ESTRADA"
        case "PCA":
            desc = "PRAÇA"
        case "ROD":
            desc = "RODOVIA"
            logr = "BR356"
        case "RUA":
            desc = "RUA"
        case "TRV":
            desc = "TRAVESSA"
        case "VDP":
            desc = ""
        case "VIA":
            desc = "VIADUTO"

    address = f"{desc} {logr}, {numi}, Belo Horizonte, Minas Gerais, Brazil"
    params = {"q": address, "api_key": api_key}

    success = False

    for t in range(2):
        try:
            query = req.get(url, params=params, timeout=10)
            query.raise_for_status()
            data = query.json()

            # cords_full_data[str(i)] = {"NOME": bar_name, "NOME_FANTASIA": bar_fantasia, "ENDERECO": address, "GEOCODE": data}
            if data:
                lat = data[0].get("lat")
                lon = data[0].get("lon")
                cords_data[str(i)] = {"NOME": bar_name, "NOME_FANTASIA": bar_fantasia, "ENDERECO": address, "LATITUDE": lat, "LONGITUDE": lon}

            if i%200 == 0:  # Evita escrita em disco todo loop
                with open(CORDS_DIR, "w", encoding="utf-8") as f:
                    json.dump(cords_data, f, ensure_ascii=False, indent=4)

            success = True
            successes += 1
            print(f"[{i}] {bar_name}: query successful")

            break

        except Exception as e:
            print(f"Failed line {i} - {bar_name}: {e}")
            time.sleep(sleep_time)

    # Falha crítica - nenhuma das tentativas sucedeu
    if success == False:
        print(f"Critical failure on line {i}")
        fails += 1

    time.sleep(sleep_time)    # Limite de consultas da API

# Dump final
with open(CORDS_DIR, "w", encoding="utf-8") as f:
    json.dump(cords_data, f, ensure_ascii=False, indent=4)

# with open(FDATA_DIR, "w", encoding="utf-8") as f:
    # json.dump(cords_full_data, f, ensure_ascii=False, indent=4)

print("Sucessos:", successes)
print("Falhas:", fails)

[17200] 60.792.336 DANIEL PEREIRA DE SOUZA: query successful
[17210] 60.898.339 FLAVIO SALTARA: query successful
[17214] 60.832.757 KARINA APARECIDA DA SILVA: query successful
[17275] 61.663.666 CAIO HENRIQUE LOPES FERREIRA: query successful
[17283] 61.801.634 RAYANE REZENDE SANTOS DE OLIVEIRA: query successful
[17289] ALTEROSAS BAR E RESTAURANTE LTDA: query successful
[17290] CURRAL DA SERRA RESTAURANTE LTDA COUNTRY CLUB: query successful
[17294] 61.653.975 DENNER CESAR FERREIRA GOMES: query successful
[17296] CLA ESPACO E CULTURA LTDA: query successful
[17394] 61.475.910 ALUISIO MACHADO DE OLIVEIRA: query successful
[17406] COPO MINEIRO LTDA: query successful
[17409] 61.598.501 NATHALIA CRISTINA PEREIRA VERISSIMO COSTA: query successful
[17437] 61.309.653 SILBERT RIBEIRO ALVES: query successful
[17503] SO JOAO BUTIQUIM LTDA: query successful
[17513] 55.119.620 IARA PERPETUO GOMES: query successful
[17527] ANDU RESTAURANTE LTDA: query successful
[17560] 61.130.451 DAIANA GONCALVES DE MEIRA: query successful
[17579] 61.887.038 JOHNATAN SOARES FERNANDES: query successful
[17586] 62.134.519 GONCALO DA CONCEICAO SACRAMENTO: query successful
[17592] 62.031.926 ANTONIO CARLOS DA COSTA FILHO: query successful
[17640] 62.169.456 GEISELAINE NATIVIDADE MARIA: query successful
[17676] TF CAFETERIA & HELADERIA LTDA: query successful
[17684] 61.912.869 ROSANGELA DE JESUS GUILHERME: query successful
[17709] 61.870.611 ANA BEATRIZ DA SILVA DAMASCENO: query successful
[17711] 61.917.564 CAROLINA MENDES DOS SANTOS: query successful
[17714] 61.964.495 JUSCELIO MARQUES: query successful
[17718] 61.847.833 RENNER HENRIQUE PEREIRA GONCALVES: query successful
[17845] 62.325.213 GABRIEL JUNIO DIAS MAXIMO: query successful
[17857] 62.201.441 DANIELLE CRISTINA ALVES DA SILVA: query successful
[17872] MOCCA S-A: query successful
[17885] REI DA FEIJOADA COMERCIO DE ALIMENTOS LTDA: query successful
[17887] REI DA FEIJOADA COMERCIO DE ALIMENTOS LTDA: query successful
[17964] 63.188.325 APARECIDA LIMA ALVES: query successful
[18054] 63.074.106 GIOVANI DEUSDEDITH DO AMARAL: query successful
[18067] 62.620.436 JUNIO VINICIUS ALVES: query successful
[18081] ADEGA NOTURNA LTDA: query successful
[18125] 62.819.011 CLEONICE DE JESUS GOMES: query successful
[18150] 62.620.592 JOSE BRAZ LEANDRO: query successful
[18158] ESPETINHOS DO PAULISTA LTDA: query successful
[18162] 62.623.303 LUANA DOS SANTOS FERREIRA: query successful
[18179] TRAILER RLM COMERCIO LTDA: query successful
[18216] RODIZA ALIMENTOS LTDA: query successful
[18227] BENZA DEUS GASTROBAR LTDA: query successful
[18246] SUPERFOODS ALIMENTACAO S.A.: query successful
[18247] SUPERFOODS ALIMENTACAO S.A.: query successful
[18287] 63.563.539 JULIO CESAR PEREIRA: query successful
[18301] 63.549.881 EMYLLE THAYANNE DE OLIVEIRA SANTOS: query successful
[18314] 63.500.894 ROSIANE DE JESUS SOUZA: query successful
[18329] ANTONIO MARCOS RAMOS DE OLIVEIRA: query successful
[18344] 63.402.509 PATRICIA SOUZA DO ESPIRITO SANTO: query successful
[18368] BAR E RESTAURANTE MASSAS BARREIRO LTDA: query successful
[18374] RLAJ SORVETERIA LTDA: query successful
[18395] AMERICAN COOKIES BHS LTDA: query successful
[18442] 63.794.442 LUIZ HENRIQUE DA SILVA DINIZ: query successful
[18454] HIGOR ESPETOS LTDA: query successful
[18460] FRUTARIA BH LTDA: query successful
[18466] GPFOODS COMERCIO DE ALIMENTOS LTDA: query successful
[18495] SORVETES GELUPE LTDA: query successful
[18578] NB SORVETES E CONFEITARIA LTDA: query successful
[18588] HS LANCHES RIO BRANCO LTDA: query successful
[18590] 64.575.063 DANIEL DARIO SANTOS DO NASCIMENTO: query successful
[18594] 64.269.994 GIZELE MARIA RODRIGUES MIRANDA: query successful
[18612] CASA CAJU LTDA: query successful
[18636] 64.289.315 WALTER MARTINS GONCALVES DE BARROS SOARES: query successful
[18658] CANTINHO DOS LANCHES LTDA: query successful
[18665] 64.071.258 AMANDA APARECIDA DE OLIVEIRA NEVES: query successful
[18673] RIBEIRO DOGUERIA LTDA: query successful
[18675] 64.214.986 WEMILLY JEREMIAS DE LIMA: query successful
[18708] JARDIM 360 LTDA: query successful
[18727] 51.148.216 RUTE LOURENCO DOS SANTOS: query successful
[18728] LA VISTA SPORTS LTDA: query successful
[18735] 63.969.875 ANA CLAUDIA SANTOS PARDIM: query successful
[18776] 63.897.339 MELISSA EMANUELE PALHARES REZENDE: query successful
[18780] 64.010.969 JULIA DE CASTRO MAIA: query successful
[18807] RESTAURANTE DA LIU LTDA: query successful
[18830] ACAI & SORVETES MUUUITO BOM LTDA: query successful
[18840] 26.798.491 MAXWELL DOS SANTOS MARTINS: query successful
[18846] 64.853.806 RIAN DIAS SANTOS ROCHA: query successful
[18861] CJM COMERCIAL LTDA: query successful
[18912] 64.713.990 GERALDO DO CARMO DE OLIVEIRA PINTO: query successful
[18947] 64.702.208 MARIA DO CARMO DE SOUZA RAMPINELI: query successful
[18982] 65.009.204 MICHAEL LENO LEAL: query successful
[18983] SOUTTO MAYOR & BRUM CAFETERIA LTDA: query successful
[18985] BAR PASSE BEM LTDA: query successful
[18991] 65.035.614 BRUNO FELIPE DE OLIVEIRA DOMINGOS: query successful
[19009] KE DELICIAS SORVETERIA E DISTRIBUIDORA LTDA: query successful
[19024] 65.545.325 ELIZABETH DANIEL DAS GRACAS BATISTA: query successful
[19040] 65.835.915 OSMAR APARECIDO DE SALES: query successful
[19049] HV BISCOITERIA LTDA.: query successful
[19153] 65.517.364 EMANUEL CLAYDERMAM RIBEIRO DA SILVA: query successful
[19168] 65.563.063 CRISTIANA DE JESUS MOURA: query successful
[19177] 65.630.871 VANDERSON BATISTA MEIRA: query successful
[19194] 65.544.598 ISABEL CRISTINA BATISTA XAVIER: query successful
[19222] AMY WINE BAR LTDA: query successful
[19268] 65.402.107 MARCOS ANTONIO DA SILVA: query successful
[19292] 65.430.220 FILIPE ELIHABE LANCA DA SILVA: query successful
[19293] CASA MIA GRILL LTDA: query successful
[19310] 65.137.467 NATHALIE DE PAULA CORREA ANDRADE: query successful
[19334] 65.319.560 GABRIELLE STEFANE ALVES DAMASCENA: query successful
[19361] FERREIRA FOODS LTDA: query successful
[19376] 65.204.929 RODRIGO QUEIROGA CARVALHO: query successful
[19448] 65.874.330 VINICIUS DE MORAES FERREIRA: query successful
[19453] 65.897.718 CARLOS SOARES RIBEIRO: query successful
[19462] 65.860.245 JOYCE NERES VALENTIM: query successful
[19481] 66.180.321 CLAUDINEI JOSE DOS SANTOS: query successful
[19484] 66.078.250 JOSISLLAYNE RODRIGUES GONCALVES: query successful
[19499] 66.102.744 ELIANE OTONI PEREIRA: query successful
[19514] 66.147.077 ROSELI PIRES PAIM: query successful
[19529] ASSADOS BARREIRO LTDA: query successful
[19539] 66.091.192 GABRIEL LUCAS DE MORAES VIEIRA: query successful
[19576] 66.668.862 ALIONAI PAULA DE CRISTO: query successful
[19578] NORRUH CAFE LTDA: query successful
[19594] 66.569.338 ANA LUIZA PEREIRA SANTANA: query successful
[19601] GRAZZIE GELATO LTDA: query successful
[19663] 66.367.172 RODRIGO LISBOA DA SILVA: query successful
[19722] 66.441.781 ELBERT DOS SANTOS: query successful
[19756] 66.254.460 ADEMIR GERALDO DE SOUZA: query successful
[19769] CABRILLO ROTTA BUTIQUIM LTDA: query successful
[19778] 66.279.626 LUIZ VITOR DOS SANTOS FERREIRA: query successful
[19798] 58.687.993 FERNANDA SANTANA DE SOUZA: query successful
[19804] BHG COMERCIO ALIMENTICIO LTDA: query successful
[19805] 13.586.653 AILTON ALVES DE SOUZA: query successful
[19861] 66.771.128 KAIQUE HUGO DOS PRAZERES DE ARAUJO: query successful
[19877] 66.797.475 RICHARD DE LIMA ALONSO: query successful
[19894] 66.869.061 RENATA DE ASSIS: query successful
[19898] 66.847.072 EVERTON NEVES: query successful
[19905] 66.803.781 GLAUCIENE LUZIA DE JESUS: query successful
[19955] 66.903.297 GUILHERME DE ALMEIDA SAMORA: query successful
[19991] 67.035.411 ERICK DIAS ANANIAS: query successful
[19998] ESQUINA 3 LTDA: query successful
[20023] 67.524.640 NATALIA DOS SANTOS SOUSA SENA: query successful
[20032] 67.699.682 THAINARA SILVA LOIOLA: query successful
[20035] FS COMERCIO E EMPREENDIMENTOS LTDA: query successful
[20040] 67.601.108 CLAUDIA APARECIDA DA SILVA NOBRE LEAL: query successful
[20043] 67.657.608 JAQUELINE AMARAL PADILHA: query successful
[20093] 67.593.521 TATILA MACEDO DE MATOS: query successful
[20122] 67.280.773 ADMILTON MARQUES DA SILVA: query successful
[20150] CAMARADA ADMINISTRACAO DE RESTAURANTES S.A.: query successful
[20159] 67.305.493 GRAZIELE VITORIA MONTEIRO MARCELINO: query successful
[20180] 67.146.007 ROBERT LOPES DA SILVA: query successful
[20188] 67.043.335 EVERTON LOPES RODRIGUES: query successful
[20218] 67.183.724 TIAGO SANTOS OLIVEIRA: query successful
[20245] 67.102.502 MARIA HELENA SOBRINHO DE PAIVA BERTOLIN: query successful
[20251] DELIVERY 356 LTDA: query successful
[20275] 67.713.998 PALOMA RIBEIRO CEZAR: query successful
[20276] ROUTE 66 PIZZAS LTDA: query successful
[20304] 67.721.767 SABRINA ALVES BENEVIDES: query successful
[20309] 67.843.467 MARIA IZABELA DA SILVA PENIDO: query successful
[20315] 67.844.767 PABLO HENRIQUE GOMES ARAUJO: query successful
[20323] V&L EMPREENDIMENTOS LTDA: query successful
[20351] 67.876.996 GIOVANNA ROBERTO NOGUEIRA: query successful
[20366] 67.976.141 CAMILA MARTINS DE OLIVEIRA PINTO: query successful
[20368] LANCHONETE PAODEQUEIJOLANDIA SERRA VERDE LTDA: query successful
[20405] 68.004.721 ADILSON MARTINS DOS SANTOS SOUSA: query successful
[20434] 68.151.780 MARIA DE JESUS RODRIGUES RAMOS SOUZA: query successful
[20468] 68.316.973 CAIO ANTONIO MOREIRA MELO: query successful
[20485] 68.320.840 BRUNO LENO LEAL: query successful
[20488] 68.366.704 JULIANA FERREIRA DE SOUZA: query successful
[20491] 68.227.835 ELAINE CRISTINA DE ALMEIDA VIANA: query successful
[20503] 68.203.182 KAREN LUIZA ARAUJO REZENDE: query successful
[20505] ROPA GASTRONOMIA LTDA: query successful
[20510] STARS COMERCIO DE BURGUER E ACAITERIA LTDA: query successful
[20570] 68.137.244 EMANUELLY CRISTINA NOVAIS SANTOS: query successful
[20581] MORIA COMERCIO DE SORVETES LTDA: query successful
[20589] PARADA BH LTDA: query successful
[20635] 68.459.285 ANA CAROLINA PEREIRA SOARES: query successful
[20650] 68.440.798 GABRIEL GOMES DUARTE: query successful
[20651] 68.441.311 DAVI SANTIAGO COZZI: query successful
[20668] 68.495.090 JACKSON EDUARDO DE FREITAS RAMOS: query successful
[20672] 68.424.141 VICTOR MANOEL SALLES: query successful
[20679] 68.498.507 LINDA LOPES PAULISTA: query successful
[20689] 68.624.306 RAILDA PEREIRA DA SILVA: query successful
[20692] 68.662.644 RAFAEL GOMES DA SILVA: query successful
[20696] 68.686.118 LUISA CARDOSO PACHECO: query successful
[20728] 68.614.113 MARIA PEREIRA DOLIA: query successful
[20767] 68.756.586 MARIA DA PENHA: query successful
[20777] 59.837.818 IGOR ALEXANDRE MARIANO: query successful
[20783] 68.736.981 SAMUEL DOS SANTOS RODRIGUES: query successful
[20794] SP LITUANIA 2026 BAR E RESTAURANTE LTDA: query successful
[20821] 68.728.180 MICHELE XAVIER DE MACEDO: query successful
[20834] 68.826.901 KAROLINA BARBOSA ALVES: query successful
[20848] 68.817.107 HELOIZA SILVA SANTOS: query successful
[20851] 68.856.212 FERNANDA DA SILVA CUNHA: query successful
Sucessos: 183
Falhas: 0

### 3- Construção de uma Nova Base de Dados
Com base nas coordenadas extraídas, agora construímos uma nova tabela com os endereços e coordenadas para ser usada na simulação.

O índice da tabela é renomeado para _old_index_ porque o índice não representa o número da linha nesta nova tabela, mas sim o número da linha correspondente na tabela antiga, para que seja possível cruzar os dados depois caso necessário.

In [15]:
# Carregamento dos dados
if os.path.exists(CORDS_DIR):
    try:
        with open(CORDS_DIR, "r", encoding="utf-8") as f:
            cords_data = json.load(f)
    except Exception as e:
        print("Unable to load previous data:", e)

new_bar_table = pd.DataFrame.from_dict(cords_data, orient='index')

# Ajustes
new_bar_table.index.name = "old_index"
new_bar_table["LATITUDE"] = new_bar_table["LATITUDE"].astype(float)
new_bar_table["LONGITUDE"] = new_bar_table["LONGITUDE"].astype(float)

new_bar_table

,NOME,NOME_FANTASIA,ENDERECO,LATITUDE,LONGITUDE
old_index,,,,,
0,BAR E CAFE DONATELO LTDA,,"AVENIDA PORTUGAL, 4316, Belo Horizonte, Minas ...",-19.843947,-43.958138
1,PALLATE COMERCIO DE PRODUTOS ALIMENTICIOS LTDA,PALLATE,"RUA VINTE E OITO DE SETEMBRO, 606, Belo Horizo...",-19.911048,-43.907020
2,FABIO KALKS KOSCKY,BAR DO FABIO,"AVENIDA EDGAR DA MATA MACHADO, 390, Belo Horiz...",-19.920171,-43.997347
3,NECTAR DA SERRA LTDA,NECTAR DA SERRA,"AVENIDA DOS BANDEIRANTES, 1839, Belo Horizonte...",-19.949169,-43.920703
4,MERCEARIA DA SERRA LTDA,BAR E MERCEARIA DA SERRA,"RUA DO OURO, 1428, Belo Horizonte, Minas Gerai...",-19.947210,-43.918542
...,...,...,...,...,...
20854,68.809.777 IRISNEIDE ALVES PEREIRA,,"RUA EMILIA MARZANO MATIAS, 115, Belo Horizonte...",-19.803473,-43.985905
20855,68.819.988 KAREN ALEXANDRA PEREIRA DA CRUZ LIMA,,"RUA ACIDENTAL, 46, Belo Horizonte, Minas Gerai...",-19.934670,-43.907813
20856,68.828.610 LUCINEIA APARECIDA FERREIRA ALVES,,"RUA BELA VISTA, 251, Belo Horizonte, Minas Ger...",-19.919168,-43.982568
20857,68.828.670 ANTONIO MENEZES DA SILVA,,"RUA ERICO VERISSIMO, 2373, Belo Horizonte, Min...",-19.815254,-43.969663
20858,SO COMBOS 2 COMERCIO LTDA,SO COMBOS,"RUA BAVIERA, 119, Belo Horizonte, Minas Gerais...",-19.887985,-43.948916

In [16]:
# Número e porcentagem de perdas de endereços durante o processo de aquisição das coordenadas
bar_og = len(bar_table)
bar_cd = len(new_bar_table)
print("Endereços originais:", bar_og)
print("Endereços extraídos:", bar_cd)
print("Perda:", bar_og - bar_cd)
print("Perda em %:", round(bar_cd/bar_og, 3))

Endereços originais: 20859
Endereços extraídos: 19867
Perda: 992
Perda em %: 0.952

In [18]:
# Salvamento do csv novo
new_bar_table.to_csv(PRC_DIR / 'new_bares.csv', index=True)
test = pd.read_csv(PRC_DIR / 'new_bares.csv')
test.tail(5)

,old_index,NOME,NOME_FANTASIA,ENDERECO,LATITUDE,LONGITUDE
19862,20854,68.809.777 IRISNEIDE ALVES PEREIRA,NaN,"RUA EMILIA MARZANO MATIAS, 115, Belo Horizonte...",-19.803473,-43.985905
19863,20855,68.819.988 KAREN ALEXANDRA PEREIRA DA CRUZ LIMA,NaN,"RUA ACIDENTAL, 46, Belo Horizonte, Minas Gerai...",-19.934670,-43.907813
19864,20856,68.828.610 LUCINEIA APARECIDA FERREIRA ALVES,NaN,"RUA BELA VISTA, 251, Belo Horizonte, Minas Ger...",-19.919168,-43.982568
19865,20857,68.828.670 ANTONIO MENEZES DA SILVA,NaN,"RUA ERICO VERISSIMO, 2373, Belo Horizonte, Min...",-19.815254,-43.969663
19866,20858,SO COMBOS 2 COMERCIO LTDA,SO COMBOS,"RUA BAVIERA, 119, Belo Horizonte, Minas Gerais...",-19.887985,-43.948916